### ISSUE TITLE
Text-to-Speech Setup

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#26]
- [x] Create text-to-speech input HTML structure
- [x] Add text-to-speech basic styles
- [x] Create speech basic functions
- [ ] Add PDF upload HTML structure
- [ ] Style PDF upload area
- [x] Add speech controls HTML
- [x] Style speech control buttons

**Comment by zioan** [comment]
PDF upload will not be implemented in this iteration.
