### ISSUE TITLE
USER STORY: Read Aloud News info

### ISSUE THREAD

**Issue by dasic002** [dasic002/2411-hackathon-team2#5]
As a **user**, I want to **hear** news **headlines and content read aloud**

## Acceptance Criteria
* The user can start or pause the lecture thanks to a button

## Tasks
- [x] Add text-to-speech controls for each article
- [x] Implement stop/pause functionality per article

**Comment by DomoMKT** [comment]
i think i can help you with that! you can find a fantastic tool to convert your texts into high-quality speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com).
